# Build stage
FROM ubuntu:22.04 AS builder

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    xz-utils \
    zip \
    libglu1-mesa \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user
RUN useradd -m -s /bin/bash flutter && \
    mkdir -p /usr/local/flutter && \
    chown -R flutter:flutter /usr/local/flutter

# Install Flutter
ENV FLUTTER_VERSION=3.24.0
ENV FLUTTER_HOME=/usr/local/flutter
ENV PATH="${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:${PATH}"

# Install Flutter as the flutter user (skip doctor to avoid Gradle issues)
RUN git clone https://github.com/flutter/flutter.git -b stable ${FLUTTER_HOME} && \
    chown -R flutter:flutter ${FLUTTER_HOME} && \
    su flutter -c "flutter config --enable-web"

WORKDIR /app
RUN chown -R flutter:flutter /app

# Copy pubspec file (lock file will be generated by flutter pub get)
COPY --chown=flutter:flutter pubspec.yaml ./

# Get dependencies as flutter user
USER flutter
RUN flutter pub get

# Copy source code
COPY --chown=flutter:flutter . .

# Build Flutter web app
RUN flutter build web --release

# Production stage - Use nginx to serve static files
FROM nginx:alpine

# Copy built files from builder
COPY --from=builder /app/build/web /usr/share/nginx/html

# Copy nginx configuration for SPA routing
RUN echo 'server { \
    listen 80; \
    server_name _; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
